//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_dip_hoc_sinh_gioi
    {
        public int idDip { get; set; }
        public int idNhanKhau { get; set; }
        public string truong { get; set; }
        public string lop { get; set; }
        public int nhom { get; set; }
        public string minhChung { get; set; }
        public bool kiemtra { get; set; }
    
        public virtual nhan_khau nhan_khau { get; set; }
        public virtual dip_hoc_sinh_gioi dip_hoc_sinh_gioi { get; set; }
    }
}
