//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ho_khau_nhan_khau
    {
        public int idHoKhau { get; set; }
        public int idNhanKhau { get; set; }
        public string quanHeChuHo { get; set; }
    
        public virtual ho_khau ho_khau { get; set; }
        public virtual nhan_khau nhan_khau { get; set; }
    }
}
