//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ho_khau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ho_khau()
        {
            this.chuyen_ho_khau = new HashSet<chuyen_ho_khau>();
            this.ho_khau_nhan_khau = new HashSet<ho_khau_nhan_khau>();
        }
    
        public int idHoKhau { get; set; }
        public int idChuHo { get; set; }
        public string tinhThanhPho { get; set; }
        public string quanHuyen { get; set; }
        public string phuongXa { get; set; }
        public string diaChi { get; set; }
        public System.DateTime ngayTao { get; set; }
        public string trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chuyen_ho_khau> chuyen_ho_khau { get; set; }
        public virtual nhan_khau nhan_khau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ho_khau_nhan_khau> ho_khau_nhan_khau { get; set; }
    }
}
