//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class khai_tu
    {
        public int idNguoiMat { get; set; }
        public int idNguoiKhai { get; set; }
        public System.DateTime ngayKhai { get; set; }
        public System.DateTime ngayMat { get; set; }
        public string liDoMat { get; set; }
    
        public virtual nhan_khau nhan_khau { get; set; }
        public virtual nhan_khau nhan_khau1 { get; set; }
        public virtual nhan_khau nhan_khau2 { get; set; }
    }
}
