//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tam_tru
    {
        public int id { get; set; }
        public int idNhanKhau { get; set; }
        public string noiThuongTru { get; set; }
        public string noiTamTru { get; set; }
        public System.DateTime tuNgay { get; set; }
        public System.DateTime denNgay { get; set; }
        public string lyDo { get; set; }
    
        public virtual nhan_khau nhan_khau { get; set; }
    }
}
